CREATE TABLE foods (
    food_id BIGINT NOT NULL AUTO_INCREMENT,
    source_food_code VARCHAR(19) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    food_name VARCHAR(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    normalized_name VARCHAR(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
    food_type CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    basis_amount DECIMAL(12,4) NOT NULL,
    basis_unit VARCHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    energy DECIMAL(12,4) NULL,
    energy_unit VARCHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    carbohydrate DECIMAL(12,4) NULL,
    carbohydrate_unit VARCHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    protein DECIMAL(12,4) NULL,
    protein_unit VARCHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    fat DECIMAL(12,4) NULL,
    fat_unit VARCHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    CONSTRAINT pk_foods PRIMARY KEY (food_id),
    CONSTRAINT uk_foods_source_food_code UNIQUE (source_food_code),
    CONSTRAINT ck_foods_source_food_code
        CHECK (source_food_code REGEXP '^[PD][0-9]{3}-[0-9]{9}-[0-9]{4}$'),
    CONSTRAINT ck_foods_food_name CHECK (CHAR_LENGTH(TRIM(food_name)) > 0),
    CONSTRAINT ck_foods_normalized_name CHECK (CHAR_LENGTH(TRIM(normalized_name)) > 0),
    CONSTRAINT ck_foods_food_type CHECK (food_type IN ('P', 'D')),
    CONSTRAINT ck_foods_food_type_code CHECK (food_type = LEFT(source_food_code, 1)),
    CONSTRAINT ck_foods_basis_amount CHECK (basis_amount = 100.0000),
    CONSTRAINT ck_foods_basis_unit CHECK (basis_unit IN ('G', 'ML')),
    CONSTRAINT ck_foods_energy_unit CHECK (energy_unit = 'KCAL'),
    CONSTRAINT ck_foods_carbohydrate_unit CHECK (carbohydrate_unit = 'G'),
    CONSTRAINT ck_foods_protein_unit CHECK (protein_unit = 'G'),
    CONSTRAINT ck_foods_fat_unit CHECK (fat_unit = 'G'),
    CONSTRAINT ck_foods_energy CHECK (energy IS NULL OR energy >= 0),
    CONSTRAINT ck_foods_carbohydrate CHECK (carbohydrate IS NULL OR carbohydrate >= 0),
    CONSTRAINT ck_foods_protein CHECK (protein IS NULL OR protein >= 0),
    CONSTRAINT ck_foods_fat CHECK (fat IS NULL OR fat >= 0),
    INDEX ix_foods_normalized_name_code (normalized_name, source_food_code)
);
